name: chrisplough
favicon: null
layout_spectrum: 0.8133
typography_spectrum: 0.07229839754290879
title: Chris Plough - Guiding entrepreneurs and startups to bring meaningful things into our world.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.693523810012266
  lightness: 0.040577609557658434
  saturation: 0.7241585704032332
  rhythmicContrast: 0.4647158174775541
purpose: []
